local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequence: 0.25
  static_map: false
  rolling_window: true
  width: 6.00
  height: 6.0
  resolution: 0.05 #0.05

  obstacle_layer:
    observation_sources: laser_scan sonar_scan
    laser_scan: {data_type: LaserScan, topic: /RosAria/S3Series_1_laserscan, sensor_frame: laser_frame, marking: true, clearing: true}
    sonar_scan: {data_type: PointCloud2, topic: /RosAria/sonar_pointcloud2, sensor_frame: base_link, marking: true, clearing: true, obstacle_range: 0.65, observation_persistence: 3}

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0
  inflation_layer:
    inflation_radius: 0.3
    cost_scaling_factor: 0.1
