controller_frequency: 30 #6.0
controller_patience: 15.0
planner_frequency: 30 # 0.4
planner_patience: 5.0

conservative_reset_dist: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: false
shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5
