final_vel_topic: /RosAria/cmd_vel
aux_vel_topic: /aux_cmd_vel
usr_cmd_vel_topic: /usr_cmd_vel
nav_cmd_vel_topic: /nav_cmd_vel
insecure_vel_topic: /insecure_cmd_vel
insecure_mode_topic: /insecure_mode
shared_mode_topic: /shared_mode
shared_mode: False
switch_rate: 20
